language: java

sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  - docker build -t blog .
  - docker tag rajhans

script:
  - docker ps | grep -q blog
  - docker login  -u rajhans953 -p rajhans.yadav
  - docker tag rajhans953/blog:latest
  - docker push
#  - pwd
#  - ls
#  - ls  /home/travis/build/rajhans995533/security/
#  

