language: java

sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  - docker build -t rajhans953/hans .
  - docker run -d -p 127.0.0.1:80:80 --name rajhans953/hans

script:
  - docker ps | grep -q rajhans953/hans
  - bash docker_push
#  - pwd
#  - ls
#  - ls  /home/travis/build/rajhans995533/security/
#  