language: java

sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install:
  - docker build -t blog .
  - docker run -d -p 127.0.0.1:80:80 --name blog blog

script:
  - docker ps | grep -q blog
  - pwd
  - ls
  - ls  /home/travis/build/rajhans995533/security/
  